sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge Group-19
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network Group-19 mongo
  - docker build -t sem_group19 .
  - docker run --network Group-19 sem_group19